### PR TITLE
Fixed error "Unknown relationship: app_lookup_by_app_id"

### PR DESCRIPTION
**Pull request by kalliste**
Right now when I create a new installation of dreamfactory from git it crashes. This seems to fix the problem.

### CODE REVIEW

**Comment by df-arif** [comment]
I have not been able to duplicate this issue. Can you let us know what procedure you are following to install it and where exactly in the installation process it crashes? Also which branch you are using?

**Comment by kalliste** [comment]
This happens on CentOS 6.7 with MySQL 5.1.73 and PHP 5.5.30 when installing from GitHub.

On a fresh install of CentOS 6.7, I first install the dependences:

#####
yum install expect git curl  mysql mysql-server httpd 
rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
yum install php55w php55w-common php55w-cli php55w-curl php55w-json php55w-mcrypt php55w-gd php55w-mbstring php55w-pdo php55w-mysqlnd
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
#####

Then I install DreamFactory:
#####
echo "CREATE DATABASE dreamfactory1" | mysql
echo "GRANT ALL ON dreamfactory1.* TO 'dreamfactory'@'localhost' IDENTIFIED BY 'dreamfactory'" | mysql

git clone https://github.com/dreamfactorysoftware/dreamfactory
cd dreamfactory
composer install --no-dev

php artisan dreamfactory:setup
php artisan dreamfactory:setup
#####

Then I run DreamFactory and open it in a browser:
#####
php artisan serve --host=0.0.0.0 --port=9001
#####

The error appears on the PHP Artisan console. In the browser I see a blank page but there is some JavaScript code there if you view the source.

**Comment by df-arif** [comment]
Can you give us more details on what were your input/output during the first and second run of php artisan dreamfactory:setup?

**Comment by kalliste** [comment]
Yes - I actually started making expect scripts for this.
I set up a MySQL database:

     echo "CREATE DATABASE dreamfactory1" | mysql
     echo "GRANT ALL ON dreamfactory1.* TO 'dreamfactory'@'localhost' IDENTIFIED BY 'dreamfactory'" | mysql


Then the first round of :setup

     **********************************************************************************************************************
     * Configuring DreamFactory...
     **********************************************************************************************************************
     Created .env file with default configuration.
     Application key [vhFZRowzjrT2FSjzuqWyUvM2FbvEMEtt] set successfully.
 
      Which database would you like to use for system tables? [sqlite]:
       [0] sqlite
       [1] mysql
       [2] pgsql
      > 11
 
      Enter your mysql Host:
      > localhost
 
      Enter your database name:
      > dreamfactory1
 
      Enter your database username:
      > dreamfactory
 
      Enter your database password:
      > dreamfactory
 
 
      Re-enter your database password:
      > dreamfactory
 
 
      Enter your Database Port [3306]:
      >
 
     Configured mysql Database
     Configuration complete!
     *************************************************** WARNING! *********************************************************
     *
     * Please take a moment to review the .env file. You can make any changes as necessary there.
     *
     * Please run "php artisan dreamfactory:setup" again to complete the setup process.
     *
     **********************************************************************************************************************

Then the second round


     Milo
     Minderbinder
     milominderbinder
     user@example.com
     password
     password

**Comment by luisbatista** [comment]
Hello,

I have this problem when make the installation from Git to my VPS server, after resolve permissions and server configurations, etc... when go to the `/dreamfactory/dist/index.htm` l get a blank page and on the browser console something like "../api/v2/system/environment" 400 error... (get also 404, 500, etc)

Then copy this "`../api/v2/system/environment`" and put in Postman app and get in the message "`Unknown relationship: app_lookup_by_app_id`" ! 

More search, and find a user telling the problem is related with table engine, is set to MyISAM and need to be **InnoDB**! 

I have to change server default mysql engine to `InnoDB`, then remove all tables in the database, make a new tables installation (`php artisan migrate --seed`), new df setup (`php artisan df:setup`) to create the Admin user, clear the cache (`php artisan cache:clear`) and then all works! Uauuu :)

Regards,
LB

**Pull request closed without merging**
