### PR TITLE
Add GDPR opt-in checkboxes at registration time.

### PR DESCRIPTION
**Pull request by sjuchno**

### CODE REVIEW

**Comment by sjuchno** [comment]
@wjgilmore I'm closing this. I guess you don't need it anymore and even if you still should have access to this branch.

**Comment by sjuchno** [comment]
@daniilly Can this PR be transfer somehow to another user please? It has been more then 2 years and I still have this in my PRs list and it would be great if I could get rid of it.

**Comment by sjuchno** [comment]
> @daniilly Can this PR be transfer somehow to another user please? It has been more then 2 years and I still have this in my PRs list and it would be great if I could get rid of it.
> 
> Same with this one [dreamfactorysoftware/df-admin-app#210](https://github.com/dreamfactorysoftware/df-admin-app/pull/210)

@wjgilmore

**Comment by daniilly** [comment]
@sjuchno, I'm apologizing for the delay in replying. I would like to assist you, but I don't have the authority to do so.

**Pull request closed without merging**
